pool:
  vmImage: 'ubuntu-latest'

container: 'golang:1.12'

variables:
  GO111MODULE: 'on'

steps:
  - script: go env
    displayName: 'Environment'

  - script: make deps
    displayName: 'Get dependencies'

  - script: make build
    displayName: 'Build'

  - script: make test >gotest.xml
    displayName: 'Test'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: gotest.xml
