pool:
  vmImage: 'ubuntu-18.04'

variables:
  project: '$(build.repository.name)'

steps:
    - displayName: 'Build'
      script: |
        docker build --target builder -t $(project)-build .
        docker run $(project)-build

    - displayName: 'Lint'
      script: |
        docker build --target linter -t $(project)-lint .
        docker run lint

    - displayName: 'Test'
      script: |
        docker build --target tester -t $(project)-test .
        docker run $(project)-test >test-results/gotest.xml

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: test-results/*.xml
