pool:
  vmImage: 'ubuntu-latest'

steps:
    - script: |
        docker build --target builder -t build .
        docker run build
      displayName: 'Build'

    - script: |
        docker build --target linter -t lint .
        docker run lint
      displayName: 'Lint'

    - script: |
        docker build --target tester -t test .
        docker run test >test-results/gotest.xml
      displayName: 'Test'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: test-results/*.xml
