pool:
  vmImage: 'ubuntu-latest'

steps:
    - script: |
        docker build --target builder -t build .
        docker run build
      displayName: 'Build'

    - script: |
        docker build --target linter -t lint .
        docker run lint
      displayName: 'Lint'

    - script: |
        docker build --target tester -t test .
        mkdir test-results
        docker run test -v gotest.xml:gotest.xml -v coverage.xml:coverage.xml
      displayName: 'Test'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: gotest.xml

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: coverage.xml
