pool:
  vmImage: 'ubuntu-latest'

container: 'golang:1.12'

variables:
  GO111MODULE: 'on'

steps:
  - script: |
      go get ./...
      go get github.com/jstemmer/go-junit-report
      go get github.com/t-yuki/gocover-cobertura
    displayName: 'Get dependencies'

  - script: go build -v ./...
    displayName: 'Build'

  - script: golangci-lint run
    displayName: 'Lint'

  - script: |
      go test -coverprofile=coverage.txt -covermode count -timeout 1s -v ./... 2>&1 | tee gotest.out
      go-junit-report <gotest.out >gotest.xml
      gocover-cobertura <coverage.txt >coverage.xml

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: gotest.xml

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: coverage.xml
