pool:
  vmImage: 'ubuntu-latest'

container: 'golang:1.12'

variables:
  GO111MODULE: 'on'
  GOLANGCI_URI: 'https://install.goreleaser.com/github.com/golangci/golangci-lint.sh'

steps:
  - script: |
      go get ./...
      go get github.com/jstemmer/go-junit-report
      go get github.com/t-yuki/gocover-cobertura
      curl -sfL $(GOLANGCI_URI)  | sh -s -- -b $(go env GOPATH)/bin v1.17.1
    displayName: 'Get dependencies'

  - script: go build -v ./...
    displayName: 'Build'

  - script: golangci-lint run
    displayName: 'Lint'

  - script: |
      go test -coverprofile=coverage.txt -covermode count -timeout 1s -v ./... 2>&1 | tee gotest.out
      cat gotest.out | go-junit-report | tee gotest.xml
      cat coverage.txt | gocover-cobertura | tee coverage.xml
    displayName: 'Test'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: gotest.xml

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: coverage.xml
