pool:
  vmImage: 'ubuntu-18.04'

variables:
  project: '$(build.repository.name)'

steps:
    - script: |
        docker build --target builder -t $(project)-build .
        docker run $(project)-build
      displayName: 'Build'

    - script: |
        docker build --target linter -t $(project)-lint .
        docker run lint
      displayName: 'Lint'

    - script: |
        docker build --target tester -t $(project)-test .
        docker run $(project)-test >test-results/gotest.xml
      displayName: 'Test'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: test-results/*.xml
