version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Install linter
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
      - run:
          name: Run linter
          command: golangci-lint run --enable-all

      - run: go build ./...

      - run: go get github.com/jstemmer/go-junit-report
      - run: mkdir ${TEST_RESULTS}
      - run: |
          trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
          go test -v ./... | tee ${TEST_RESULTS}/go-test.out
      - store_test_results:
          path: /tmp/test

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
